### PR TITLE
Compatible with multi

### PR DESCRIPTION
**Pull request by redegg89**
Just made the mod compatible with online. Also references changed because VRUI and colors weren't being referenced

### CODE REVIEW

**Comment by redegg89** [comment]
Didn't read the first part of the readme sorry

**Comment by Naquino14** [comment]
I meant pull it to the repo i forked it from lol, feel free to reopen it.

**Comment by redegg89** [comment]
Oh ok

**Comment by redegg89** [comment]
Good news: I seem to have fixed it

Bad news: in doing so, I also destroyed the menu

**Comment by Naquino14** [comment]
image

**Comment by Naquino14** [comment]
im grabbing the logs rn. can you commit to your repository so I can see whats up?

**Comment by redegg89** [comment]
Sure

**Comment by Naquino14** [comment]
well, the file is 30 mb so heres the zip.
[2021.01.31.21.21.33.log.gz](https://github.com/Naquino14/CustomSaberPlugin/files/5919879/2021.01.31.21.21.33.log.gz)

**Comment by Naquino14** [comment]
Whats strange is that the mod wasnt logging anything...

**Comment by redegg89** [comment]
I noticed that too. I think we have 3 options:

- remove the menu entirely   

Not the best, because you can't change your saber in-game

- re-write the menu   

No more of that bug, but it would probably be a lot of work

- inform the people about the problem and how to avoid it   

Once again, not ideal because after changing sabers, they'd have to restart to avoid the problem

**Comment by Naquino14** [comment]
id make a choice but I have no idea whats causing the bug in the first place.

**Comment by redegg89** [comment]
Fair enough. It's still possible that up to this point, it's been something other than the previews. My guess is that they might be causing a memory leak

**Comment by Naquino14** [comment]
lemme understand what you did, you deleted the saber previews page to fix the game running like how I had quoted it?

**Comment by redegg89** [comment]
I think so

**Comment by Naquino14** [comment]
I wanna test v4.4.15 myself to see what's up. You said you didn't have any issues when you first tested it right?

**Comment by redegg89** [comment]
I was experiencing the issue, but only after going into the saber menu

**Comment by Naquino14** [comment]
oh

**Pull request merged**
